apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: tomkl/backend-securesup:latest 
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "mysql-service" 
        - name: DB_NAME
          value: "securesup_db"
        - name: DB_USER
          value: "root"
        - name: DB_PASS
          value: "root_password"